services:
  mariadb:
    image: mariadb:11
    container_name: maplog-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: maplog_dev
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - maplog-mariadb-data:/var/lib/mysql

volumes:
  maplog-mariadb-data: