apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: map-log-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gusgh075/k8s-manifests.git'
    targetRevision: HEAD
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: map-log
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
